# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sanskar Gupta
title: BSc Data science student (2nd year)
email: sanskargupta15@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  sanskar-16
linkedin_username: sanskargupta
# instagram_username: jekyll
# twitter_username: jekyll
# stackoverflow_username: "00000001"
# facebook_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb

# Additional icon links
additional_links:
- title: CV link
  icon: fas fa-globe
  url: sanskar-16.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a BSc Data Science student, looking for a placement/internship opportunity. I have dedicated much of my life to community support work and have excellent customer service skills as a result of being a good communicator. I speak three languages and I have extensive programming skills, which I enjoy using for open-sourced coding projects. I have worked on lots of volunteering projects and various jobs throughout my studies at the university.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Essex
        caption: October 2020 - Present
        sub_title: Resident Assistant
        # link: https://www.essex.ac.uk/life/accommodation/living-on-campus/residence-life
        description: | # this will include new lines to allow paragraphs
          - Creating a sense of community through social opportunities and befriending.
          - Using admin and organisational skills for facilitating flat agreements  
          - Problem solving and dialogue within student accommodation using negotiation and listening skills.
          - Building inclusive residential and campus wide communities and assist in the creation of an environment in which     students not only live and learn but also grow.
          - Creative thinking to come up with programmes with social values for residents, promoting and running those events.
          - Mental health awareness.

      - layout: left
        title: Living Ambition - Lifeways
        caption: February 2020 - Present
        sub_title: Support worker
        # link: https://www.lifeways.co.uk/
        description: |
          - Working as a support worker by helping the service users carry out their day-to-day task.
          - Being punctual to relieve colleagues from previous shifts.
          - Responsibly help them take their medications correctly and on time.
          - Make food with/for them, helps me learn about different people and their interests.
          - Working part-time as and when needed by the services I am listed under. Keeps me determined to work better and harder every day.
      
      - layout: left
        title: University of Essex
        sub_title: Accommodation representative
        caption: October 2019 - June 2020
        # link: https://www.lifeways.co.uk/
        description: | 
          - Maintain my own room to show it as a model room for visiting parents and new students.
          - Fill in timesheets in a particular time frame to get paid for the shifts held.
      
      - layout: left
        title: Theobroma - Food of the Gods
        sub_title: Team member
        caption: May 2019 - August 2019
        # link: https://theobroma.in/
        description: |
          - Worked as a Team Member to provide quality service.
          - Coordinated with the team to deliver in the best interest of the customer.
          - Well Experienced in waiting tables, closing shift, managing orders.
          - Responsibly handle cash whenever needed.
          - Converse with customers for feedback on the service provided and how can it be improved.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Essex
        caption: 2019 - 2023
        sub_title: BSc Data Science and Analytics
        description: | # this will include new lines to allow paragraphs
          Modules taken -
          - Object oriented programming (Java, Python)
          - Data structure and Algorithms
          - Artificial intelligence
          - Database managament and Information storage/retrieval systems
          - Calculus, Complex number and Matrices
          - Discrete Mathematics
          - Optimisation (LP)
          - Statistics I, Statistics II, Survival Analysis (R)
          - Team project Challenge (Kaggle housing project)(Machine Learning)
          Grade Recieved (First year) - 73% [2:1 or above]

      - layout: left
        title: Delhi Public School
        caption: 2017 - 2019
        sub_title: PCM (CBSE)
        description: |
          Subjects taken -
          - Physics
          - Chemistry
          - Math
          - English
          - Computer Science
          - Pyhiscal Education
          Grade Recieved - 89%(A)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Covid-19 Modelling and forecasting tool
        link: https://cseegit.essex.ac.uk/2020_ce291/ce291_team02
        # link_text: Project Website
        additional_links:
          - title:  CV
            icon: fab fa-github
            url: github.com/sanskar-16
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest projects I have worked on.
        description: | # this will include new lines to allow paragraphs
          I started this project in my second year at the university as a part of the challenge week team project. I worked alongside 6 other people to produce a minimum viable product in 3 months, which eventually leads to the final product.

  - title: Skills
    layout: text
    content: |
      - Languages known - English, Hindi, Spanish (Beginner)
      - Version control (Git), Project management (Jira) 
      - Languages (Python, MySQL, R, MATLAB, Java, HTML, C++(Begineer).
      - Concepts (Machine Learning, Statistics, AI).
      - Conversant with Windows, Mac, MS office & other internet-based applications.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data and computer science, some of my other interests and hobbies are:
      - Sports and fitness - helps me keep active and agile. I am passionate about football.
      - Gaming - I participate in local tournaments for call of duty: mobile. Helps me relax and meet new people with same interests.
      - Attending webinars and conferences like NDC.
      - Cycle touring - Exploring nearby areas, and do long rides.
      - Listening and working with music - I love to play keyboard and drums in my free time.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
